platform :ios, '8.0'

target 'Permissions' do

	# Comment this line if you're not using Swift and don't want to use dynamic frameworks
  	use_frameworks!

	# Pods for Permissions
	pod 'SwiftyBeaver'
	pod 'PureLayout'
	pod 'TaylorSource', '~> 2'
	pod 'Operations/+AddressBook'
	pod 'Operations/+Photos'

end

target 'PermissionsTests' do
	inherit! :search_paths
	# Pods for testing
end
